[package]
name = "assembler"
version = "0.1.0"
authors = ["Keringar <git@keringar.xyz>"]

[dependencies]
gfx = "0.15"
gfx_device_gl = "0.14"
gfx_window_glutin = "0.15"
glutin = "0.7"
specs = "0.8"
cgmath = "0.13"
slog = "2.0"
slog-term = "2.0.0-4.0"
slog-async = "2.0"